

INSERT INTO works (title, title_jp, type, genre, description, image_url, release_year, episodes_chapters, air_status) VALUES
('Demon Slayer',    '鬼滅の刃',           'anime', 'Action',        'Tanjiro becomes a demon slayer to avenge his family and cure his sister Nezuko who was turned into a demon.',                                  'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',   2019, '44 eps',   'Completed'),
('Attack on Titan', '進撃の巨人',          'anime', 'Action',        'Humanity lives inside cities surrounded by enormous walls to protect themselves from Titans — gigantic humanoid creatures.',                     'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',     2013, '87 eps',   'Completed'),
('Jujutsu Kaisen',  '呪術廻戦',           'anime', 'Action',        'High schooler Yuji Itadori joins a secret organization of Jujutsu Sorcerers to kill a powerful Curse named Ryomen Sukuna.',                    'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',  2020, '48 eps',   'Completed'),
('Vinland Saga',    'ヴィンランド・サガ',   'anime', 'Historical',    'Young Thorfinn seeks revenge against the mercenary leader Askeladd who killed his father in Viking-age Europe.',                               'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg',  2019, '48 eps',   'Completed'),
('One Piece',       'ワンピース',          'manga', 'Adventure',     'Monkey D. Luffy sets sail on the high seas to become the King of the Pirates and find the legendary treasure known as the One Piece.',          'https://cdn.myanimelist.net/images/manga/2/253146l.jpg',     1997, '1117 ch',  'Ongoing'),
('Berserk',         'ベルセルク',          'manga', 'Dark Fantasy',  'Guts, a lone mercenary, fights his way through a nightmarish dark medieval world cursed by demons and his own grim destiny.',                   'https://cdn.myanimelist.net/images/manga/1/157897l.jpg',     1989, '374 ch',   'Ongoing'),
('Blue Period',     'ブルーピリオド',       'manga', 'Slice of Life', 'A sharp but aimless delinquent discovers a passion for art and dedicates himself to passing the entrance exam for Tokyo University of the Arts.', 'https://cdn.myanimelist.net/images/manga/2/204827l.jpg',     2017, '84 ch',    'Ongoing'),
('Chainsaw Man',    'チェンソーマン',       'manga', 'Action',        'Denji merges with his pet devil Pochita and becomes Chainsaw Man, working as a devil hunter for Public Safety while chasing simple dreams.',     'https://cdn.myanimelist.net/images/manga/3/216464l.jpg',     2018, '194 ch',  'Ongoing');
