INSERT INTO works (title, title_jp, type, genre, description, image_url, release_year, episodes_chapters, air_status) VALUES
('Demon Slayer',                         '鬼滅の刃',                          'anime', 'Action',        'After his family is slaughtered and his sister turned into a demon, Tanjiro Kamado joins the Demon Slayer Corps to avenge his family and find a cure for his sister Nezuko.',                                              'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',   2019, '44 eps',   'Completed'),
('Attack on Titan',                      '進撃の巨人',                         'anime', 'Action',        'In a world where humanity lives behind giant walls to protect themselves from Titans, young Eren Yeager vows to exterminate all Titans after his mother is devoured by one.',                                             'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',     2013, '87 eps',   'Completed'),
('Jujutsu Kaisen',                       '呪術廻戦',                           'anime', 'Action',        'Yuji Itadori swallows a cursed object to save his classmates and becomes the host of a powerful Curse named Ryomen Sukuna, forcing him into the world of Jujutsu sorcerers.',                                          'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',  2020, '48 eps',   'Completed'),
('Vinland Saga',                         'ヴィンランド・サガ',                  'anime', 'Historical',    'Young Thorfinn grows up in a time of war between England and Denmark. After his father is killed by the mercenary Askeladd, he vows to defeat him in a duel.',                                                          'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg',  2019, '48 eps',   'Completed'),
('One Piece',                            'ワンピース',                          'manga', 'Adventure',     'Monkey D. Luffy, a boy who gained the properties of rubber after eating a Devil Fruit, sets sail with his crew to find the legendary treasure One Piece and become King of the Pirates.',                               'https://cdn.myanimelist.net/images/manga/2/253146l.jpg',     1997, '1117 ch',  'Ongoing'),
('Berserk',                              'ベルセルク',                          'manga', 'Dark Fantasy',  'Guts, a former mercenary, travels the dark medieval world as a lone swordsman haunted by a Brand of Sacrifice, seeking revenge against the man who betrayed him.',                                                      'https://cdn.myanimelist.net/images/manga/1/157897l.jpg',     1989, '374 ch',   'Ongoing'),
('Blue Period',                          'ブルーピリオド',                       'manga', 'Slice of Life', 'Yatora Yaguchi, a straight-A student, discovers the magic of painting and decides to pursue the prestigious Tokyo University of the Arts despite having no experience.',                                                'https://cdn.myanimelist.net/images/manga/2/204827l.jpg',     2017, '84 ch',    'Ongoing'),
('Chainsaw Man',                         'チェンソーマン',                       'manga', 'Action',        'Denji is a young man burdened with debt who kills devils to pay it off. After merging with his devil-dog Pochita, he gains the power to transform into the Chainsaw Man.',                                             'https://cdn.myanimelist.net/images/manga/3/216464l.jpg',     2018, '194 ch',   'Ongoing'),
('Fullmetal Alchemist: Brotherhood',     '鋼の錬金術師 FULLMETAL ALCHEMIST',    'anime', 'Adventure',     'Brothers Edward and Alphonse Elric search for the Philosopher\'s Stone after a failed alchemy experiment costs them their bodies and pulls them into a conspiracy that threatens their world.',                          'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg',   2009, '64 eps',   'Completed'),
('Death Note',                           'デスノート',                          'anime', 'Mystery',       'Light Yagami finds a notebook that can kill anyone whose name is written in it, starting a tense battle of intellect against the detective known as L.',                                                                'https://cdn.myanimelist.net/images/anime/1079/138100l.jpg',  2006, '37 eps',   'Completed'),
('Spy x Family',                         'SPY×FAMILY',                         'anime', 'Comedy',        'A spy, an assassin, and a telepath form a fake family for a secret mission, but each hides their real identity from the others.',                                                                                       'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg',  2022, '12 eps',   'Completed'),
('Frieren: Beyond Journey\'s End',       '葬送のフリーレン',                    'anime', 'Fantasy',       'After defeating the Demon King, the long-lived elf mage Frieren begins a new journey to understand the human bonds she once took for granted.',                                                                        'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg',  2023, '28 eps',   'Completed'),
('My Hero Academia',                     '僕のヒーローアカデミア',               'anime', 'Action',        'Izuku Midoriya is born without powers in a world full of heroes, but a chance meeting with All Might gives him the opportunity to train at U.A. High.',                                                                 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg',     2016, '13 eps',   'Completed'),
('Naruto',                               'ナルト',                              'anime', 'Adventure',     'Naruto Uzumaki, a mischievous young ninja shunned by his village, trains to become Hokage and earn the respect of everyone around him.',                                                                               'https://cdn.myanimelist.net/images/anime/1141/142503l.jpg',  2002, '220 eps',  'Completed'),
('Haikyu!!',                             'ハイキュー!!',                        'anime', 'Sports',        'Shoyo Hinata joins Karasuno High School\'s volleyball team and learns what it takes to compete alongside and against talented rivals.',                                                                                 'https://cdn.myanimelist.net/images/anime/7/76014l.jpg',      2014, '25 eps',   'Completed'),
('Your Name.',                           '君の名は。',                           'anime', 'Drama',         'Two teenagers living separate lives mysteriously begin swapping bodies, setting them on a search for one another across distance and time.',                                                                             'https://cdn.myanimelist.net/images/anime/5/87048l.jpg',      2016, '1 film',   'Completed'),
('Cowboy Bebop',                         'カウボーイビバップ',                   'anime', 'Sci-Fi',        'A crew of bounty hunters travels through space chasing criminals while each member carries unfinished business from the past.',                                                                                         'https://cdn.myanimelist.net/images/anime/4/19644l.jpg',      1998, '26 eps',   'Completed'),
('Steins;Gate',                          'STEINS;GATE',                        'anime', 'Sci-Fi',        'A self-proclaimed mad scientist and his friends accidentally discover a way to send messages to the past, pulling them into a dangerous fight over time itself.',                                                        'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg',  2011, '24 eps',   'Completed'),
('Hunter x Hunter',                      'HUNTER×HUNTER',                      'anime', 'Adventure',     'Gon Freecss becomes a Hunter to search for his father, meeting friends and rivals through exams, battles, and dangerous journeys.',                                                                                     'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg',   2011, '148 eps',  'Completed'),
('Code Geass: Lelouch of the Rebellion', 'コードギアス 反逆のルルーシュ',        'anime', 'Sci-Fi',        'Lelouch gains the power to command others and leads a rebellion against the Holy Britannian Empire while hiding behind the masked identity Zero.',                                                                       'https://cdn.myanimelist.net/images/anime/5/50331l.jpg',      2006, '25 eps',   'Completed'),
('One Punch Man',                        'ワンパンマン',                        'anime', 'Action',        'Saitama is a hero who can defeat any enemy with one punch, leaving him bored as he searches for a challenge worthy of his strength.',                                                                                   'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',     2015, '12 eps',   'Completed'),
('Mob Psycho 100',                       'モブサイコ100',                        'anime', 'Action',        'Shigeo Kageyama is a quiet middle schooler with overwhelming psychic powers, trying to grow as a person without relying on his abilities.',                                                                             'https://cdn.myanimelist.net/images/anime/8/80356l.jpg',      2016, '12 eps',   'Completed'),
('Violet Evergarden',                    'ヴァイオレット・エヴァーガーデン',     'anime', 'Drama',         'A former child soldier becomes an Auto Memory Doll, writing letters for others while learning the meaning of emotions and love.',                                                                                       'https://cdn.myanimelist.net/images/anime/1795/95088l.jpg',   2018, '13 eps',   'Completed'),
('Kaguya-sama: Love is War',             'かぐや様は告らせたい',                 'anime', 'Romance',       'Two brilliant student council leaders are in love, but both refuse to confess first and turn romance into a battle of strategy.',                                                                                       'https://cdn.myanimelist.net/images/anime/1295/106551l.jpg',  2019, '12 eps',   'Completed'),
('Cyberpunk: Edgerunners',               'サイバーパンク エッジランナーズ',      'anime', 'Sci-Fi',        'In Night City, a street kid becomes an edgerunner and risks everything for survival, freedom, and the people he cares about.',                                                                                         'https://cdn.myanimelist.net/images/anime/1818/126435l.jpg',  2022, '10 eps',   'Completed'),
('Bocchi the Rock!',                     'ぼっち・ざ・ろっく！',                 'anime', 'Comedy',        'A socially anxious guitarist joins a band and slowly learns to connect with others through music and live performances.',                                                                                               'https://cdn.myanimelist.net/images/anime/1448/127956l.jpg',  2022, '12 eps',   'Completed'),
('Tokyo Ghoul',                          '東京喰種トーキョーグール',             'anime', 'Horror',        'Ken Kaneki becomes half-ghoul after a deadly encounter and is forced to survive between human society and the hidden world of ghouls.',                                                                                 'https://cdn.myanimelist.net/images/anime/1498/134443l.jpg',  2014, '12 eps',   'Completed'),
('Sword Art Online',                     'ソードアート・オンライン',             'anime', 'Fantasy',       'Players trapped inside a virtual reality MMORPG must clear the game to escape, with death in the game meaning death in real life.',                                                                                   'https://cdn.myanimelist.net/images/anime/11/39717l.jpg',     2012, '25 eps',   'Completed');

-- Demo account (password: demo1234)
INSERT INTO users (username, email, password, role, bio) VALUES
('demo', 'demo@anitrack.com', '$2y$12$ou3PyFD/W8Dc8yDNImsQfeeb8QmSP0EBqZ492/VigbBnm0uMm8.W6', 'user', 'Just a demo account exploring AniTrack. Feel free to look around!');

-- Demo library entries (various statuses)
INSERT INTO user_library (user_id, work_id, status, rating, note) VALUES
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Frieren: Beyond Journey\'s End'),  'Completed',      10, 'Absolute masterpiece.'),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Fullmetal Alchemist: Brotherhood'), 'Completed',      10, NULL),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Steins;Gate'),                      'Completed',       9, 'Mind-bending story.'),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Vinland Saga'),                    'Completed',       9, NULL),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Attack on Titan'),                 'Completed',       8, NULL),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Demon Slayer'),                    'Completed',       8, NULL),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Jujutsu Kaisen'),                  'Watching',     NULL, NULL),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Hunter x Hunter'),                 'On Hold',      NULL, 'Paused at the Chimera Ant arc.'),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'Berserk'),                         'Plan to Read', NULL, NULL),
((SELECT id FROM users WHERE username = 'demo'), (SELECT id FROM works WHERE title = 'One Piece'),                       'Plan to Read', NULL, NULL);

-- Demo reviews
INSERT INTO reviews (work_id, user_id, rating, body, user_status) VALUES
((SELECT id FROM works WHERE title = 'Frieren: Beyond Journey\'s End'),  (SELECT id FROM users WHERE username = 'demo'), 10, 'One of the most emotionally mature anime I have ever seen. The pacing is deliberate and the themes of time, grief, and connection hit hard.', 'Completed'),
((SELECT id FROM works WHERE title = 'Steins;Gate'),                      (SELECT id FROM users WHERE username = 'demo'),  9, 'Slow start but the payoff is incredible. The time travel logic is tight and the characters are genuinely compelling.', 'Completed');
